use pizzaanalysis;

-- Retrieve the total number of orders placed.
		SELECT COUNT(*) AS total_orders FROM orders ;

-- Business Use: Measures overall order volume to evaluate total business activity.
-- Result: 21350 Orders

-- Calculate the total revenue generated from pizza sales.
SELECT  ROUND(SUM(order_details.quantity * pizzas.price),2) AS total_sales
FROM order_details 
JOIN pizzas ON pizzas.pizza_id = order_details.pizza_id;	

-- Business Use: Measures total sales revenue generated by the business.
-- Result: 8,17,860.05


-- Identify the highest-priced pizza.

SELECT pizza_type_id, price FROM pizzas ORDER BY price DESC LIMIT 1;
SELECT pizza_type_id,price FROM pizzas WHERE price=(SELECT MAX(price)FROM pizzas);

-- Business Use: Identifies the premium-priced pizza for product and pricing analysis.
-- Result: The Greek Pizza - 35.95


-- Identify the most common pizza size ordered.
SELECT pizzas.size,COUNT(order_details.order_details_id) AS 'p count'
FROM pizzas  JOIN order_details ON pizzas.pizza_id = order_details.pizza_id 
GROUP BY pizzas.size ORDER BY 2 DESC;

-- Business Use: Identifies customer size preferences to support inventory and product planning.
-- Insight: Large (L) was the most preferred pizza size with 18,526 orders, while XL
-- and XXL showed significantly lower demand with only 544 and 28 orders.

-- List the top 5 most ordered pizza types along with their quantities.
SELECT pizza_type.name,sum(order_details.quantity) as quantity ,pizzas.price
 FROM pizza_type JOIN pizzas ON pizzas.pizza_type_id=pizza_type.pizza_type_id  
 JOIN order_details ON order_details.pizza_id=pizzas.pizza_id
group by pizza_type.name,pizzas.price ORDER BY quantity DESC LIMIT 5;

-- Business Use: Identifies the best-selling pizza types to support menu and demand planning.
--  Insights: Big meat Pizza Is Top-Seller with 1914 Quantity


-- Join the necessary tables to find the total quantity of each pizza category ordered.
	
    select pizza_type.category,sum(order_details.quantity) as quantity
    from pizzas join pizza_type on pizza_type.pizza_type_id=pizzas.pizza_type_id   -- ACTUAL ANSWER 
    join order_details on order_details.pizza_id=pizzas.pizza_id
    group by pizza_type.category ORDER BY quantity desc ;

-- Business Use: Compares demand across pizza categories to identify the most popular product segments.
    
    --  Individual Pizza Quantity Price And Sale
	SELECT order_details.pizza_id,SUM(order_details.quantity),pizzas.price,SUM(order_details.quantity) * pizzas.price AS total_sale
    FROM order_details JOIN pizzas ON pizzas.pizza_id=order_details.pizza_id
    GROUP BY order_details.pizza_id,pizzas.price order by 2 desc, 4 desc;
-- Business Use: Calculates sales generated by each pizza to identify high-performing products.


-- Determine the distribution of orders by hour of the day.
select hour(order_time) as hours ,count(order_id)
from orders group by hours order by 2 DESC;
-- Business Use: Identifies peak ordering hours to support staffing and operational planning.
--  Peak Time : Afternoon- Evening ( 12 to 8)

-- Group the orders by date and calculate the average number of pizzas ordered per day.
		with cte as (select orders.order_date,SUM(order_details.quantity) as quantity
        from orders join order_details on order_details.order_details_id=orders.order_id
        group by orders.order_date)
        SELECT *,(SELECT AVG(quantity) from cte) from cte;
        --  Shows Total Order Per Day and Average Order Per Day ( 60.77 Pizzas per day)

-- Business Use: Measures average daily pizza demand to support inventory and capacity planning.
-- Result: 60.77


-- Determine the top 3 most ordered pizza types based on revenue.
		SELECT order_details.pizza_id,SUM(order_details.quantity)*MAX(pizzas.price) AS total_sale
        FROM order_details JOIN pizzas ON pizzas.pizza_id=order_details.pizza_id 
        GROUP BY order_details.pizza_id ORDER BY total_sale DESC LIMIT 3;

        --  HERE PIZZAID IS STILL A COLUMN AND NOT AGG SO WE GROUP IT

-- Business Use: Identifies the highest revenue-generating pizzas to support product and sales strategy.


-- Calculate the percentage contribution of each pizza type to total revenue.
			select pizza_type.category,
            round(sum(order_details.quantity*pizzas.price) /
            (select sum(order_details.quantity * pizzas.price) from pizzas 
            join order_details on order_details.pizza_id=pizzas.pizza_id) *100,2)
            as total_sale_percent
            from pizza_type join pizzas on pizzas.pizza_type_id=pizza_type.pizza_type_id
            join order_details on order_details.pizza_id=pizzas.pizza_id
            group by pizza_type.category;

-- Business Use: Shows each pizza category's contribution to total revenue to identify 
-- the most valuable product segments.



--  Which pizza has the highest average quantity ordered per order?
with cte as 
(SELECT od.order_id,pt.name as pizza_name ,sum(od.quantity) as total_quantity
FROM order_details od join pizzas p on p.pizza_id=od.pizza_id 
join pizza_type pt on pt.pizza_type_id=p.pizza_type_id
GROUP BY od.order_id,pt.name)
SELECT pizza_name,AVG(total_quantity) from cte GROUP BY pizza_name ;

--  Find the top-selling pizza for each day of the week.
with cte as 
(SELECT DAYNAME(o.order_date),pt.name,SUM(od.quantity*p.price) as total_revenue,
ROW_NUMBER() OVER(PARTITION by DAYNAME(o.order_date) order by SUM(od.quantity*p.price) DESC) as rnk
from order_details od join orders o on o.order_id=od.order_id
join pizzas p on p.pizza_id=od.pizza_id
JOIN pizza_type pt  ON pt.pizza_type_id = p.pizza_type_id
GROUP BY 1,2 )
SELECT * from cte WHERE rnk =1;
-- result : Top Selling Pizzas By the Weekdays 

-- Which category has the greatest difference between its highest-selling and lowest-selling pizza?
with cte as 
(SELECT pt.category,pt.name,SUM(od.quantity*p.price) as total_revenue
from order_details od join orders o on o.order_id=od.order_id
join pizzas p on p.pizza_id=od.pizza_id
JOIN pizza_type pt  ON pt.pizza_type_id = p.pizza_type_id GROUP BY pt.category,pt.name)
SELECT category,MAX(total_revenue)-MIN(total_revenue) from cte GROUP BY category;
-- result : Classic Catgeory


-- Find pizzas that were ordered less but generated above-average total revenue.
-- ( we gonna use condn total quantity<avg(quantity) and toatl rev>avg(rev)
WITH pizza_stats AS (
    SELECT pt.name AS pizza_name,
        SUM(od.quantity) AS total_quantity,
        SUM(od.quantity * p.price) AS total_revenue
    FROM order_details od
    JOIN pizzas p ON p.pizza_id = od.pizza_id JOIN pizza_type pt ON pt.pizza_type_id = p.pizza_type_id
    GROUP BY pt.name)
SELECT * FROM pizza_stats
WHERE total_quantity < ( SELECT AVG(total_quantity) FROM pizza_stats )
AND total_revenue > ( SELECT AVG(total_revenue) FROM pizza_stats);
-- Result=The Mexicana Pizza,The Five Cheese Pizza,The Five Cheese Pizza